# Generated by Django 3.2 on 2022-10-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_active_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
