# Generated by Django 3.2 on 2022-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_active_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
