# Generated by Django 3.2 on 2022-12-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_auto_20221129_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default='2022-12-01 12:56:10'),
        ),
    ]
