# Generated by Django 3.2 on 2022-11-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='percentage',
        ),
    ]
