# Generated by Django 3.2 on 2022-11-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_remove_voucher_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='percentage',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
