# Generated by Django 3.2 on 2022-11-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_voucher_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='percentage',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
