# Generated by Django 3.2 on 2022-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deluxe',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
