# Generated by Django 3.2 on 2022-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_deluxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=1000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='www00000', max_length=254),
            preserve_default=False,
        ),
    ]
