# Generated by Django 3.2 on 2022-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_pairing',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='grapes',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(max_length=50),
        ),
    ]
