# Generated by Django 3.2 on 2022-11-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221119_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_pairing',
            field=models.CharField(max_length=254),
        ),
    ]
